name: bus_master
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  mobile_scanner: ^2.1.0
  permission_handler: ^11.0.1
  csv: ^5.1.1
  cloud_firestore: ^3.3.0
  http: ^0.13.3
  tflite_flutter: ^0.8.0
  tflite_flutter_helper: ^0.2.0
  provider: ^6.1.1
  firebase_core: ^1.10.0
  firebase_storage: ^10.3.3
  shared_preferences: ^2.0.10

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/bus_turning.gif
    - images/day_bus.gif
    - images/bus.gif
    - images/bus_icon.png
    - images/bus_1.gif
    - images/bus-image.gif
    - images/bus-ride.gif
    - model/time_prediction_TF_LITE.tflite

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
          style: normal
